### ISSUE TITLE
Image thumbnail required

### ISSUE THREAD

**Issue by jsonchi** [AizazAZ/Android-Ultra-Photo-Selector#5]
Check this link:http://developer.android.com/training/displaying-bitmaps/load-bitmap.html

**Comment by AizazZaidee** [comment]
com.photoselector.ui.PhotoSelectorActivity

ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(getApplicationContext()).defaultDisplayImageOptions(defaultDisplayImageOptions)
                .memoryCacheExtraOptions(480, 800).threadPoolSize(5).build();

**Comment by jsonchi** [comment]
What I mean is that we should generate a sample bitmap not placeholder icon.

**Comment by AizazZaidee** [comment]
Please feel free to send merge request.
