### ISSUE TITLE
PhotoSelectorActivity.KEY_MAX problem

### ISSUE THREAD

**Issue by msmtech-maker** [AizazAZ/Android-Ultra-Photo-Selector#8]
hi
i set ...
intent.putExtra(PhotoSelectorActivity.KEY_MAX, 3);
but more than 3 image can be selected;

**Comment by AizazZaidee** [comment]
User this method
com.photoselector.util.CommonUtils.launchActivityForResult(Activity context,
        Class<?> activity, int requestCode, int maxImage)

**Comment by msmtech-maker** [comment]
thanks dude...
but its not working...
